
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscalevote
  namespace: default
spec:
  maxReplicas: 8
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voteapp
  targetCPUUtilizationPercentage: 70
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
  status:
    observedGeneration: 1
    lastScaleTime: 
      currentReplicas: 1
      desiredReplicas: 1
    currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageUtilization: 0
          averageValue: 0



